<template>
  <ice-scrollbar :max-height="490" style="width: 300px;">
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
  </ice-scrollbar>
</template>

<script setup lang="ts">
import { IceScrollbar } from "saturn-ui";
import "saturn-ui/lib/theme-default/IceScrollbar.css";
</script>
