<template>
  <IceScrollbar :max-height="490" style="width: max-content;">
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
    <div>这是一个滚动条</div>
  </IceScrollbar>
</template>

<script setup lang="ts">
import { IceScrollbar } from "saturn-ui";
import "saturn-ui/lib/theme-default/IceScrollbar.css";
</script>
